### ISSUE TITLE
Consider using Grayskull and `pip check` to update/validate dependencies

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-neo-feedstock#30]
To simplify updating dependency constraints, it may be worth [configuring Grayskull in conda-forge.yml]( https://conda-forge.org/docs/maintainer/conda_forge_yml/#bot ) like so

```yaml
bot:
  inspection: update-grayskull
```

This way the bot will refresh dependencies during updates as well

<hr>

When doing this, would recommend adding [`pip check`]( https://conda-forge.org/docs/maintainer/adding_pkgs/#pip-check ) to the tests at the same time

```yaml
test:
  requires:
    - pip
    ...
  commands:
    - pip check
    ...
  ...
```
